### ISSUE TITLE
Display uploaded image

### ISSUE THREAD

**Issue by Sitetools** [jamesbolitho/silverstripe-frontenduploadfield#4]
Hi James,
Thank you for your great Addon.
I am uploading an image via a front end form, the form is saved to a DataObject, this all works great.
When I come to presenting the front end form fields to the user to edit, the images doesn't display and when the form is submitted the previously saved image is lost.

How can I display a previously saved image to the user on a front end form?
How can I prevent the previously saved image from being empty when the form is next updated?

Cheers

Robin

**Comment by jamesbolitho** [comment]
Hi Robin,

Thank you for reporting this issue.  

I will take a look into it when I can along with some pending updates I have planned.

Thanks,


James

**Comment by jamesbolitho** [comment]
Hi Robin,

I have looked into this and tracked down the issue with the way the field was populating the thumbnail images.  I have updated the upload field and it is working from my tests. 

There are a couple of things you need to do to get this to work with your dataobject.  Below is an example of extending the member dataobject and adding a profile photo:

```
class CustomMemberExtension extends DataExtension 
{
    private static $has_many = [
          'ProfilePhoto' => Image::class
    ];
    private static $owns = [
          'ProfilePhoto'
    ];
	
    public function updateCMSFields(FieldList $fields) 
    {
            $fields->removeByName('ProfilePhoto'); 
            $fields->addFieldToTab('Root.Main', $upload = new UploadField('ProfilePhoto', 'Profile Image'));
            $upload->setAllowedFileCategories('image/supported');
            $sizeMB = 5; // 5 MB
            $size = $sizeMB * 1024 * 1024; // 5 MB in bytes
            $upload->getValidator()->setAllowedMaxFileSize($size);
            $upload->setIsMultiUpload(true);
    }
}
```

In your form when you declare your front end upload field you can specify your Dataobject that has your image relation in the setValue function as the second paramater (in this case I am using the current user that is logged in):

`$upload1 = UploadField::create('ProfilePhoto','Profile photos:')->setValue(null, Member::CurrentUser())`

In your form processing function you then just need to save into your dataobject for example:

```
$CurrentMember = Member::CurrentUser();
$form->saveInto($CurrentMember);
$CurrentMember->write();
```

This should work with $has_one as well you just need to remove ->setIsMultiUpload(true) from your upload field and set ->setAllowedMaxFileNumber(1) for example.


If your form fields don't map exactly to your Dataobject you will need to map them yourself e.g.

```
$CurrentMember->FirstName = $data['FirstName'];
$CurrentMember->Surname = $data['Surname'];

//$has_one relation
if(isset($data['ProfilePhoto']['Files'])) $CurrentMember->ProfilePhotoID = $data['ProfilePhoto']['Files'][0];

//$has_many relation
if(isset($data['ProfilePhoto']['Files']))
{
     $IDs = $data['ProfilePhoto']['Files'];
     foreach($IDs as $ID){
          $file = File::get()->byID($ID);
          if($file) $CurrentMember->ProfilePhoto()->add($file);
     }
}
```

Hope that helps.

Thanks,


James

**Comment by Sitetools** [comment]
Thanks you James, I didn't need to make any changes, the new updates have done the trick.
Much appreciated.
Cheers

Robin

**Comment by Sitetools** [comment]
Another question.
I have an image on a front end form, it's a has_one.
I upload and image and save - perfect. The thumbnail displays and I can save the form without loosing the image. - Perfect.
How do I swap/replace the saved image in the front end form?
I can upload another image but it has a red border and a cross with an error warning "you can not upload any more files".
Is this a permissions issue, a config issue?

Cheers

Robin

**Comment by jamesbolitho** [comment]
Hi Robin,

Glad it is working for you now.

On the other question you can use the following config on your upload field: 
`$upload1->setRemoveFiles(true);`

This allows you to delete the image that is already in place so you can upload a new one.

Hope that helps.

Thanks,


James

**Comment by jamesbolitho** [comment]
I am closing this issue as I believe it is now resolved. Thanks, James
