### ISSUE TITLE
Critical Security vulnerability

### ISSUE THREAD

**Issue by robertclarkson** [jamesbolitho/silverstripe-frontenduploadfield#6]
in the remove() function the user just has to specify a valid file ID and that file is then deleted.

This means that someone can cycle through all the IDs from 1 upwards and delete all the files on the server.

**Comment by jamesbolitho** [comment]
Thanks for taking the time to report this.  I had already implemented a fix a while back on another project but forgot to apply it to this repository, my bad!  Anyway I have now updated this repository to make the remove function more secure.

**Comment by robertclarkson** [comment]
Nice work mate! Chur

**Comment by jamesbolitho** [comment]
You are welcome.
